### ISSUE TITLE
[Admin] - Create AdminGetAll

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#14]
## Description

Create `AdminGetAll`  use case.

## Requirement funcional

- [x] Should get all admins

## Bussines rules

- [x] Should not get all admins if not authenticated 

## Task

- [x] Create UseCase
- [x] Create Repository implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
