### ISSUE TITLE
[Middlewares] - Add AdminRole

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#17]
## Description

Add `AdminRoleMiddleware`.

## Requirement funcional

- [x] Should verify if user is admin

## Bussines rules

- [x] Should not allow access if user is not admin role

## Task

- [x] Create Middleware
- [x] Add middleware on get admin profile route
- [x] Test Route
