### ISSUE TITLE
[Admin] - Create AdminUpdate

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#19]
## Description

Create `AdminUpdate` use case.

## Requirement funcional

- [x] Should update admin data

## Requirement not funcional
- [x] Should encrypter new password

## Bussines rules

- [x] Should not update if email is invalid
- [x] Should not update if email is already registered
- [x] Should not update if password length less than 6 characters
- [x] Should not update if name length less than 3 characters
- [x] Should update data that is provided

## Task

- [x] Create UseCase
- [x] Add Repository implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
