### ISSUE TITLE
[AcademicYear] - Add AcademicYearCreate

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#22]
## Description

Add  `AcademicYearCreate` use case.

## Requirement funcional

- [x] Should create a new academic year

## Bussines rules

- [x] Should not create new academic year if name is less than 4 characters
- [x] Should not create new academic year if year not valid year
- [x] Should not create a new academic year if it already exists 

## Task

- [x] Create Model
- [x] Create Schema
- [x] Create UseCase
- [x] Create Repository
- [x] Create Repository implementation
- [x] Add number validation on validator
- [x] Implement number validation on adapter
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
