### ISSUE TITLE
[AcademicYear] - Create AcademicYearGetAll

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#24]
## Description

Create `Add AcademicYearGetAll` use case.

## Requirement funcional

- [ ] Should get all academic years

## Bussines rules

- [ ]  Should not get all academic years if not authenticated

## Task

- [ ] Create UseCase
- [ ] Create Repository implementation
- [ ] Create Controller
- [ ] Refactor Code
- [ ] Create Route
