### ISSUE TITLE
[AcademicYear] - Create AcademicYearGetById

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#25]
## Description
Create `AcademicYearGetById` use case.

## Requirement funcional
- [x] Should get academic year by id

## Bussines rules
- [x] Should not get academic year if academic year not found
- [x] Should receive id by params
- [x] Should not get academic year  if not authenticated
- [x] Should not get academic year  if user is not admin

## Task
- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
