### ISSUE TITLE
[AcademicYear] - Create AcademicYearUpdate

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#28]
## Description

Create `AcademicYearUpdate` use case. 

## Requirement funcional

- [x] Should update academic year

## Bussines rules
- [x] Should not update if name is less than 4 characters
- [x] Should not update if year not valid year
- [x] Should not update if name already exists
- [x] Should receive id by params
- [x] Should not get academic year  if not authenticated
- [x] Should not get academic year  if user is not admin

## Task
- [x] Add update method on repository
- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
