### ISSUE TITLE
[Admin] - Create register

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#3]
## Description

Create use case for register admin.

## Requirement funcional

- [x] Should register a new admin user

## Requirement not funcional
- [x] Should encrypt  password

## Bussines rules

- [x] Should not register if email is exists
- [x] Should not register is not name is provided
- [x] Should not register is not email is provided
- [x] Should not register is not password is provided

## Task

- [x] Create UseCase
- [x] Add Repository implementation
- [x] Add Adapters implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
