### ISSUE TITLE
[AcademicYear] - Create AcademicYearDelete

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#32]
## Description

Create `AcademicYearDelete` use case.

## Requirement funcional

- [x] Should delete academic year

## Bussines rules

- [x] Should not delete if academic year not found
- [x] Should receive id by params
- [x] Should not get academic year  if not authenticated
- [x] Should not get academic year  if user is not admin

## Task

- [x] Add delete method on repository
- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
