### ISSUE TITLE
[AcademicYearCreate]  -  Associate academic year to admin

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#34]
## Description

Associate academic year to admin on create.

## Requirement funcional

- [ ] Should associate academic year to admin on create

## Task

- [ ] Create push method on repository
- [ ] Add push on UseCase
- [ ] Add populate field `academicYears` on `AdminProfile`
