### ISSUE TITLE
[AcademicTerm] - Add AcademicTermCreate

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#41]
## Description

Add `AcademicTermCreate` use case.

## Requirement funcional

- [x] Should create a new academic term
- [x] Should associate academic term to admin on create

## Bussines rules
- [x] Should not create a new academic term if fields name, description e duration not provided
- [x] Should not create a new academic term if it already exists
- [x] Should not create academic term if not authenticated
- [x] Should not create academic term if user is not admin

## Task

- [x] Create Model
- [x] Create Schema
- [x] Create UseCase
- [x] Create Repository
- [x] Create Repository implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
