### ISSUE TITLE
[AcademicTerm] - Create AcademicTermGetAll

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#42]
## Description

Create Add `AcademicTermGetAll` use case.

## Requirement funcional

- [x] Should get all academic terms

## Bussines rules

- [x]  Should not get all academic years if not authenticated
- [x] Should not get all academic years if user is not admin

## Task

- [x] Create UseCase
- [x] Create Repository implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
