### ISSUE TITLE
[AcademicTerm] - Create AcademicTermGetById

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#43]
## Description

Create `AcademicTermGetById` use case.

## Requirement funcional

- [x] Should get academic term by id

## Bussines rules

- [x] Should not get academic term if not found
- [x] Should receive id by params
- [x] Should not get academic term if not authenticated
- [x] Should not get academic term if user is not admin

## Task

- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
