### ISSUE TITLE
[AcademicTerm] - Create AcademicTermUpdate

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#44]
## Description

Create `AcademicTermUpdate` use case

## Requirement funcional

- [x] Should update academic term

## Bussines rules

- [x] Should receive id by params
- [x] Should not update if name already exists
- [x]  Should not update if academic term not found
- [x] Should not update  if not authenticated
- [x] Should not update if user is not admin

## Task

- [x] Add update method on repository
- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
