### ISSUE TITLE
[AcademicTerm] - Create AcademicTermDelete

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#48]
## Description

Create `AcademicTermDelete` use case.

## Requirement funcional

- [x] Should delete academic term
- [x] Should disassociate academic term to admin on delete

## Bussines rules

- [x] Should not delete if academic term not found
- [x] Should receive id by params
- [x] Should not delete academic term  if not authenticated
- [x] Should not delete academic term  if user is not admin

## Task

- [x] Add delete method on repository
- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
