### ISSUE TITLE
[Admin] - Create login

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#5]
## Description

Create login use case.

## Requirement funcional
- [x] Should make login
- [x] Should generate access token

## Requirement not funcional

- [x] Should compare password with bcrypt
- [x] Should generate access token with JsonWebToken
 

## Bussines rules

- [x] Should not make login if email is not provided
- [x] Should not make login if password is not provided
- [x] Should not make login if email or password is invalid

## Task
- [x] Add Validations 
- [x] Create UseCase
- [x] Create Adapters implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
