### ISSUE TITLE
[Admin] - Add validations on AdminRegister

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#6]
## Description

Add missing validations on AdminRegister.

## Requirement funcional

- [x] Should validation fields

## Bussines rules

- [x] Should not register if email is invalid
- [x] Should not register if password length less than 6 characters
- [x] Should not register if name length less than 3 characters

## Task

- [x] Add Validation on UseCase
- [x] Add implementations on UseCase
- [x] Add Controller tests
- [x] Test Route
