### ISSUE TITLE
[Teacher] -  Add TeacherRegister

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#61]
## Description
Add `Add TeacherRegister` use case.

## Requirement funcional
- [x] Should register a new teacher
- [x] Generate auto ID

## Requirement not funcional
- [x] Should encrypt password

## Bussines rules
- [x] Should not register if email is invalid
- [x] Should not register if password length less than 6 characters
- [x] Should not register if name length less than 3 characters
- [x] Should not register if email is already register

## Task
- [x] Create Model
- [x] Create Schema
- [x] Create function for generate teacher ID
- [x] Create Repository
- [x] Create UseCase
- [x] Create Repository implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
