### ISSUE TITLE
[Teacher] - Add TeacherLogin

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#63]
## Description
Add `TeacherLogin` use case.

## Requirement funcional
- [x] Should generate access token

## Requirement not funcional
- [x] Should compare password with bcrypt
- [x] Should generate access token with JsonWebToken

## Bussines rules
- [x] Should not login if email is not provided
- [x] Should not login if password is not provided
- [x] Should not login if email or password is invalid

## Task
- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
