### ISSUE TITLE
[Teacher] - Create TeacherGetAll

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#67]
## Description

Create `TeacherGetAll` use case.

## Requirement funcional

- [x] Should get all teachers

## Bussines rules

- [x]  Should not get all teachers if not authenticated
- [x] Should not get all teachers if user is not admin

## Task
- [x] Add Repository method
- [x] Create UseCase
- [x] Create Repository implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
