### ISSUE TITLE
[Teacher] - Create TeacherGetById

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#68]
## Description

Add description here.

## Requirement funcional

- [x] Should get teacher by id

## Bussines rules

- [x] Should not get if teacher not found
- [x] Should receive id by params
- [x] Should not get if not authenticated
- [x] Should not get if user is not admin

## Task

- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
