### ISSUE TITLE
[Teacher] - Create TeacherGetProfile

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#69]
## Description

Create `TeacherGetProfile` use case.

## Requirement funcional

- [x] Should get teacher profile info

## Bussines rules

- [x] Should get id by access token
- [x] Should not get if teacher not found
- [x] Should not get if not authenticated
- [x] Should not get if user is not teacher

## Task

- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
