### ISSUE TITLE
[Teacher] - Create TeacherUpdate

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#70]
## Description

Create `TeacherUpdateProfile` use case.

## Requirement funcional

- [x] Should update teacher data

## Requirement not funcional

- [x]  Should encrypter new password with JsonWebToken

## Bussines rules

- [x] Should not register if email is invalid
- [x] Should not register if email is already register
- [x] Should not register if name length less than 3 characters
- [x] Should not register if password length less than 6 characters
- [x] Should encrypter password if password is provided
- [x] Should not update if user is not authenticated
- [x] Should not update if user is not teacher

## Task
- [x] Create Repository method
- [x] Add Repository implementation
- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
