### ISSUE TITLE
[Student] - Add StudentRegister

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#75]
## Description

Add `StudentRegister`.

## Requirement funcional

- [ ] Should register a new student

## Requirement not funcional

- [ ] Should encrypt password

## Bussines rules

- [ ] Should not ...

## Task

- [ ] Create Model
- [ ] Create Schema
- [ ] Create Repository
- [ ] Create UseCase
- [ ] Create Repository implementation
- [ ] Create Controller
- [ ] Refactor Code
- [ ] Create Route
