### ISSUE TITLE
[Student] - Create StudentLogin 

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#76]
## Description

Create `StudentLogin`. 

## Requirement funcional

- [x] Should generate access token

## Requirement not funcional

- [x] Should compare password with Bcrypt
- [x] Should generate access token with JsonWebToken

## Bussines rules

- [x] Should not login if email is not provided
- [x] Should not login if password is not provided
- [x] Should not login if email or password is invalid

## Task

- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
