### ISSUE TITLE
[Validation] - Add Validator

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#8]
## Description

Add `Validator`.

## Requirement funcional

- [x] Should validate if email is valid
- [x] Should validate if length is valid

## Requirement not funcional

- [x] Should make validations with [zod](https://zod.dev/)

## Bussines rules

- [x] Length validation should receive min and max

## Task

- [x] Add Adapter
