### ISSUE TITLE
[Student] - Create StudentGetAll

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#85]
## Description

 Create `StudentGetAll`.

## Requirement funcional

- [x] Should get all students

## Bussines rules

- [x]  Should not get all students if not authenticated
- [x] Should not get all students if user is not admin

## Task
- [x] Add Repository method
- [x] Create UseCase
- [x] Create Repository implementation
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
