### ISSUE TITLE
[Student] - Create StudentGetById

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#86]
## Description

Create `StudentGetById`.

## Requirement funcional

- [x] Should get student by id

## Bussines rules

- [x] Should not get if student not found
- [x] Should receive id by params
- [x] Should not get if not authenticated
- [x] Should not get if user is not admin

## Task

- [x] Create UseCase
- [x] Create Controller
- [x] Refactor Code
- [x] Create Route
