### ISSUE TITLE
[Student] - Create StudentGetProfile

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#87]
## Description

Create `StudentGetProfile`.

## Requirement functional

- [ ] Should get student profile info

## Bussines rules

- [ ] Should get id by access token
- [ ] Should not get if student not found
- [ ] Should not get if not authenticated
- [ ] Should not get if user is not student or admin

## Task

- [ ] Create UseCase
- [ ] Create Controller
- [ ] Refactor Code
- [ ] Create Route
