### ISSUE TITLE
[Docs] - Add API documentation

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#91]
## Description

Add API documentation.

## Requirement functional

- [x] Should generate documentation

## Requirement not functional

- [x] Should auto generate documentation with [Swagger Autogen](https://github.com/davibaltar/swagger-autogen)

## Task
- [x] Config Swagger 
- [x] Config Swagger Autogen
- [x] Create doc for admin routes
- [x] Create doc for academic term routes
- [x] Create doc for academic year routes
- [x] Create doc for student routes
- [x] Create doc for teacher routes
