### ISSUE TITLE
[Docs] - Add README

### ISSUE THREAD

**Issue by d3vlopes** [d3vlopes/school-management#94]
## Description
Add `README.MD` with project informations.

## Task
- [x] Create about section 
- [x] Create objetive section
- [x] Create learning section
- [x] Create tools section
- [x] Create demostration section
- [x] Create installation section
